#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["TrueLayer.Pokedex.WebApi/TrueLayer.Pokedex.WebApi.csproj", "TrueLayer.Pokedex.WebApi/"]
RUN dotnet restore "TrueLayer.Pokedex.WebApi/TrueLayer.Pokedex.WebApi.csproj"
COPY . .
WORKDIR "/src/TrueLayer.Pokedex.WebApi"
RUN dotnet build "TrueLayer.Pokedex.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TrueLayer.Pokedex.WebApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TrueLayer.Pokedex.WebApi.dll"]